import os
import subprocess
import tempfile
from pathlib import Path


# ============================================================
# Agent 4 — Compiler
# ============================================================
# Responsibility:
# 1. Receive source code generated by Agent 2.
# 2. Identify the programming language.
# 3. Compile the code when compilation is required.
# 4. Report compilation success or failure.
#
# Supported languages:
# - Python
# - C++
# - Java
# ============================================================


def compile_code(code: str, language: str) -> dict:
    """
    Agent 4 compiles the source code according to the
    programming language.

    Python:
        No compilation is required.
        The file is checked for syntax errors.

    C++:
        Uses g++ to compile the source code.

    Java:
        Uses javac to compile the source code.
    """

    language = language.strip().lower()

    try:
        with tempfile.TemporaryDirectory() as temp_dir:

            temp_path = Path(temp_dir)

            # ==================================================
            # PYTHON
            # ==================================================

            if language in ["python", "python3"]:
                source_file = temp_path / "solution.py"

                source_file.write_text(
                    code,
                    encoding="utf-8"
                )

                result = subprocess.run(
                    ["python", "-m", "py_compile", str(source_file)],
                    capture_output=True,
                    text=True,
                    timeout=10
                )

                if result.returncode == 0:
                    return {
                        "success": True,
                        "language": "Python",
                        "message": "Python syntax check passed.",
                        "error": ""
                    }

                return {
                    "success": False,
                    "language": "Python",
                    "message": "Python compilation/syntax check failed.",
                    "error": result.stderr.strip()
                }


            # ==================================================
            # C++
            # ==================================================

            elif language in ["c++", "cpp", "cplusplus"]:

                source_file = temp_path / "main.cpp"
                executable_file = temp_path / "main.exe"

                source_file.write_text(
                    code,
                    encoding="utf-8"
                )

                result = subprocess.run(
                    [
                        "g++",
                        str(source_file),
                        "-o",
                        str(executable_file)
                    ],
                    capture_output=True,
                    text=True,
                    timeout=15
                )

                if result.returncode == 0:
                    return {
                        "success": True,
                        "language": "C++",
                        "message": "C++ compilation successful.",
                        "error": ""
                    }

                return {
                    "success": False,
                    "language": "C++",
                    "message": "C++ compilation failed.",
                    "error": result.stderr.strip()
                }


            # ==================================================
            # JAVA
            # ==================================================

            elif language == "java":

                source_file = temp_path / "Main.java"

                source_file.write_text(
                    code,
                    encoding="utf-8"
                )

                result = subprocess.run(
                    [
                        "javac",
                        str(source_file)
                    ],
                    capture_output=True,
                    text=True,
                    timeout=15
                )

                if result.returncode == 0:
                    return {
                        "success": True,
                        "language": "Java",
                        "message": "Java compilation successful.",
                        "error": ""
                    }

                return {
                    "success": False,
                    "language": "Java",
                    "message": "Java compilation failed.",
                    "error": result.stderr.strip()
                }


            # ==================================================
            # UNSUPPORTED LANGUAGE
            # ==================================================

            else:
                return {
                    "success": False,
                    "language": language,
                    "message": "Unsupported programming language.",
                    "error": (
                        f"Agent 4 currently supports "
                        f"Python, C++, and Java. "
                        f"Received: {language}"
                    )
                }

    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "language": language,
            "message": "Compilation timed out.",
            "error": "The compiler exceeded the time limit."
        }

    except FileNotFoundError as e:
        return {
            "success": False,
            "language": language,
            "message": "Required compiler/interpreter was not found.",
            "error": str(e)
        }

    except Exception as e:
        return {
            "success": False,
            "language": language,
            "message": "Unexpected compiler error.",
            "error": str(e)
        }